### ISSUE TITLE
missing build requirements

### ISSUE THREAD

**Issue by hdepres** [symbolibre/symbolibre#1]
I inaugurate (First!) the issues with some missing build requirements (on Debian testing):
libmpfi-dev
libgsl-dev
libntl-dev
libfltk1.3-dev

**Comment by nchappe** [comment]
Thanks! These look like giac/xcas build dependencies, they should be needed only if you want to build giac yourself. Is that what you did?

**Comment by hdepres** [comment]
No, during the build phase it requires the following files:
mpfr.h
mpfi.h
gsl/gsl_vector.h
I don't remember for the other packages

**Comment by lephe** [comment]
Giac's `gen.h` includes `<mpfr.h>` and `<mpfi.h>`, and `vecteur.h` includes `<gsl/gsl_vector.h>`. So it sounds like either Giac exposes low-level macros and relies on the user's compiler to unfold them and generate the proper MPFR/MPFI/GSL code, or the header was just left there for convenience.

Either way this causes all of these libraries to be passed on as build dependencies to the user application. We should add them to our build dependencies, both in the README and the documentation for the OS generation.

**Comment by hdepres** [comment]
Yep it seems.
Here is the error:

In file included from /usr/include/giac/giac.h:7,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/editiontree/EditionTree.hpp:10,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/editiontree.hpp:7,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/cas/MathContext.hpp:7,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/cas/MathContext.cpp:4:
/usr/include/giac/gen.h:58:10: fatal error: mpfi.h: Aucun fichier ou dossier de ce type
   58 | #include <mpfi.h>
      |          ^~~~~~~~

**Comment by hdepres** [comment]
And the two others :

In file included from /usr/include/giac/giac.h:12,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/editiontree/EditionTree.hpp:10,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/editiontree.hpp:7,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/cas/MathContext.hpp:7,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/cas/MathContext.cpp:4:
/usr/include/giac/modpoly.h:25:10: fatal error: NTL/ZZXFactoring.h: Aucun fichier ou dossier de ce type
   25 | #include <NTL/ZZXFactoring.h>
      |          ^~~~~~~~~~~~~~~~~~~~

In file included from /usr/include/giac/giac.h:37,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/editiontree/EditionTree.hpp:10,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/editiontree.hpp:7,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/cas/MathContext.hpp:7,
                 from /home/hd/Documents/ArchivesM1/projetIntegre/symbolibre/lib/symbolibre/cas/MathContext.cpp:4:
/usr/include/giac/plot.h:34:10: fatal error: FL/Enumerations.H: Aucun fichier ou dossier de ce type
   34 | #include <FL/Enumerations.H>
      |

**Comment by lephe** [comment]
fltk is quite painful, we might be able to work around the dependency if there are configure macros to disable support.

Does it compile correctly once you install these four libraries?

**Comment by hdepres** [comment]
Yes, it compiles, and it launched after i installed it.

**Comment by nchappe** [comment]
> Giac's gen.h includes <mpfr.h> and <mpfi.h>, and vecteur.h includes <gsl/gsl_vector.h>. So it sounds like either Giac exposes low-level macros and relies on the user's compiler to unfold them and generate the proper MPFR/MPFI/GSL code, or the header was just left there for convenience.

These are conditional includes, and the branches only get compiled if you have a `giac/config.h`, which I did not when I tested on an Ubuntu chroot (because of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972827). This explains why it worked without them for me.

@hdepres Can you post your `/usr/(local/)include/giac/config.h` if you have one, and the output of `apt show libgiac-dev` if you installed giac from apt?

**Comment by hdepres** [comment]
# apt show libgiac-dev
Package: libgiac-dev
Version: 1.6.0.31+dfsg1-1
Status: install ok installed
Priority: optional
Section: libdevel
Source: giac
Maintainer: Debian Science Maintainers <debian-science-maintainers@alioth-lists.debian.net>
Installed-Size: 41,1 MB
Depends: libgiac0 (= 1.6.0.31+dfsg1-1)
Homepage: https://www-fourier.ujf-grenoble.fr/~parisse/giac.html
Download-Size: inconnu
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Computer Algebra System C++ library - Development files
 Giac is a computer algebra system, following the development of the CAS for HP
 calculators. It has fast implementation of algorithms for polynomial
 operations, and compatibility mode with Maple or Mupad CAS as well as TI
 calculators.
 .
 This package contains the header files, static libraries, and other
 development files needed to build software that uses giac.

config.h :https://pastebin.com/TqZwjPgA

**Comment by lephe** [comment]
For the record (assuming this was the question here), neither `libgiac0` nor its dependencies depend on any development packages in the Raspbian repositories.

These repositories don't have `config.h`, but that's on Bullseye. [On Sid](https://packages.debian.org/sid/libgiac0) version 1.6.0.25+dfsg1-2 of `libgiac0` is pulled, which includes installing `config.h`. I assume this is the way forward.

Since it's unlikely that Giac packages have been modified specifically for Raspbian, I assume the dependencies are the same in Debian Sid. In which case these development packages are (optional) dependencies since release 1.6.0.25+dfsg1-2 but have not yet been marked as such.

**Comment by nchappe** [comment]
@hdepres From your apt output it seems you installed giac from debian unstable, not testing (if I read packages.debian.org correctly, giac is not packaged in testing), this explains why you have a giac/config.h.

I just added the missing deps in https://github.com/symbolibre/symbolibre/commit/63ce7a544c3f0e8f2c2bb0ab30afccdaca48ec19.

> For the record (assuming this was the question here), neither libgiac0 nor its dependencies depend on any development packages in the Raspbian repositories.

I think libgiac-dev (not libgiac0) should depend on all these packages (and more), this may be a Debian bug.

**Comment by lephe** [comment]
Thanks for the update.

> I think libgiac-dev (not libgiac0) should depend on all these packages (and more), this may be a Debian bug.

I agree. If the dependencies on MPFR, MPFI and GSL were optional this might have been difficult (can you specify an AND-pair as optional?) but since they are explicitly required all the dev variants should be added to libgiac-dev.

Should we report this to the packaging team?

**Comment by nchappe** [comment]
> Should we report this to the packaging team?

Probably. As for this issue, let's close it.

**Comment by lephe** [comment]
Submitted as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976067.

**Comment by lephe** [comment]
The missing dependencies have been added upstream in version 1.6.0.41+dfsg1-1. See [the changelog](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976067#10) and [the new list of dependencies](https://packages.debian.org/sid/libgiac-dev) for libgiac-dev in unstable.

This is still only in unstable so we won't be able to remove the additional packages from both the README and the documentation until the new version is migrated to testing (which we can monitor [in the tracker for the giac source package](https://tracker.debian.org/pkg/giac)).

**Comment by lephe** [comment]
The missing dependencies have been [added in Sid](https://packages.debian.org/sid/libgiac-dev) so we should be able to remove them from the README and documentation. Is that fine?
